export const backOptions = [
  { value: "Jetpack", label: "Jetpack" },
  { value: "Back Basket", label: "Back Basket" },
  { value: "Brown Backpack", label: "Brown Backpack" },
  { value: "Red Backpack", label: "Red Backpack" },
  { value: "Blue Backpack", label: "Blue Backpack" },
  { value: "Teal Backpack", label: "Teal Backpack" },
  { value: "Black Cape", label: "Black Cape" },
  { value: "Red Cape", label: "Red Cape" },
  { value: "White Cape", label: "White Cape" },
  { value: "No Back", label: "No Back" },
];

export const hatOptions = [
  { value: "Pirate Hat", label: "Pirate Hat" },
  { value: "Sombrero", label: "Sombrero" },
  { value: "Cowboy Hat", label: "Cowboy Hat" },
  { value: "Red Beret", label: "Red Beret" },
  { value: "Halo", label: "Halo" },
  { value: "Barbarian's Helm", label: "Barbarian's Helm" },
  { value: "Bard's Cap Forward", label: "Bard's Cap Forward" },
  { value: "Cleric's Hat", label: "Cleric's Hat" },
  { value: "Druid's Horns", label: "Druid's Horns" },
  { value: "Fighter's Galea", label: "Fighter's Galea" },
  { value: "Monk's Bald Head", label: "Monk's Bald Head" },
  { value: "Paladin's Helm", label: "Paladin's Helm" },
  { value: "Ranger's Hat", label: "Ranger's Hat" },
  { value: "Rogue's Mask", label: "Rogue's Mask" },
  { value: "Sorcerer's Flames", label: "Sorcerer's Flames" },
  { value: "Wizard's Hat", label: "Wizard's Hat" },
  { value: "Chef Hat", label: "Chef Hat" },
  { value: "Santa Hat", label: "Santa Hat" },
  { value: "Straw Hat", label: "Straw Hat" },
  { value: "Turban", label: "Turban" },
  { value: "Apple", label: "Apple" },
  { value: "Beanie", label: "Beanie" },
  { value: "Black Hat", label: "Black Hat" },
  { value: "Pumpkin", label: "Pumpkin" },
  { value: "No Hat", label: "No Hat" },
];

export const weapons = [
  { value: "Crystal Staff", label: "Crystal Staff" },
  { value: "Trident", label: "Trident" },
  { value: "Scythe", label: "Scythe" },
  { value: "Ranger's Bow & Arrow", label: "Ranger's Bow & Arrow" },
  { value: "Paladin's Shield", label: "Paladin's Shield" },
  { value: "Druid's Stave", label: "Druid's Stave" },
  { value: "Monk's Spell-book", label: "Monk's Spell-book" },
  { value: "Cleric's Staff", label: "Cleric's Staff" },
  { value: "Rogue's Daggers", label: "Rogue's Daggers" },
  { value: "Barbarian's Axe", label: "Barbarian's Axe" },
  { value: "Fighter's Sword", label: "Fighter's Sword" },
  { value: "Bard's Guitar", label: "Bard's Guitar" },
  { value: "Sorcerer's Wand", label: "Sorcerer's Wand" },
  { value: "Wizard's Staff", label: "Wizard's Staff" },
  { value: "Club", label: "Club" },
  { value: "Mace", label: "Mace" },
  { value: "Scimitar", label: "Scimitar" },
  { value: "Kukri", label: "Kukri" },
  { value: "Hammer", label: "Hammer" },
  { value: "Spear", label: "Spear" },
  { value: "Hatchet", label: "Hatchet" },
  { value: "Boxing Gloves", label: "Boxing Gloves" },
  { value: "Spade", label: "Spade" },
  { value: "Pickaxe", label: "Pickaxe" },
  { value: "Knife", label: "Knife" },
  { value: "Money Bag", label: "Money Bag" },
];
export const eyeColors = [
  { value: "Red-eyed", label: "Red-eyed" },
  { value: "Black-eyed", label: "Black-eyed" },
];
export const backgroundOptions = [
  { value: "Coral", label: "Coral" },
  { value: "Green", label: "Green" },
  { value: "Orange", label: "Orange" },
  { value: "Pink", label: "Pink" },
  { value: "Purple", label: "Purple" },
  { value: "Thistle", label: "Thistle" },
];
export const skinOptions = [
  { value: "Albino", label: "Albino" },
  { value: "Mink Blue", label: "Mink Blue" },
  { value: "Chocolate", label: "Chocolate" },
  { value: "Grey", label: "Grey" },
  { value: "Beige", label: "Beige" },
  { value: "Cream", label: "Cream" },
];
